# Site settings
title:          Seobew's Blog
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://seobew.github.io"

# Author
author:
  name:         seobew
  url:          https://seobew.github.io
  email:        seobew@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
